name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v1
    with:
    ref: master
    
  deploy:      
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: deploy to prod
      run: echo deployment complete
